#!/bin/bash
dir=/usr/share/openvpn
if [[ $EUID -ne 0 ]]; then
	echo "Please run with sudo."
	exit 1
fi
start(){
	sudo openvpn $dir/WafflesExploit.ovpn&
}
stop(){
	id=$(pgrep openvpn)
	sudo kill $id 1>/dev/null
}
if [[ $1 == "start" ]]; then
	start
	echo "OpenVPN Started"
fi
if [[ $1 == "stop" ]]; then
	stop
	echo "OpenVPN Stopped"
fi
if [[ $1 == "restart" ]]; then
	stop
	start
	echo "OpenVPN Restarted"
fi
