#!/bin/bash
dir=/usr/share/openvpn
if [[ $EUID -ne 0 ]]; then
	echo "Please run with sudo."
	exit 1
fi
if [[ $1 == "start" ]]; then
	sudo openvpn $dir/WafflesExploit.ovpn&
	echo "OpenVPN Started"
fi
if [[ $1 == "stop" ]]; then
	id=$(pgrep openvpn)
	sudo kill $id
	echo "OpenVPN Closed"
fi
